name: packaging

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cross-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      #matrix:
      #  os_image: [ 'almalinux:8', 'almalinux:9', 'registry.suse.com/suse/sle15:15.5' ]
      matrix:
        include:
          - os_image: 'almalinux:8'
            arch: 'x86_64'
            runs_on: 'ubuntu-latest'
          - os_image: 'almalinux:8'
            arch: 'aarch64'
            runs_on: 'ubuntu-24.04-arm'
        architecture: ['x86_64', 'aarch64']
        package: ["panhandle"]

    container:
      image: ${{ matrix.os_image }}

    steps:
      - name: Install Base Tools (Container)
        run: |
          if command -v dnf &> /dev/null; then
            if [ "${{ matrix.architecture }}" = "x86_64" ]; then
              dnf install -y gcc openssl-devel pkgconf-pkg-config binutils
            fi
          elif command -v zypper &> /dev/null; then
            if [ "${{ matrix.architecture }}" = "x86_64" ]; then
              zypper install -y gcc gcc7 libopenssl-3-devel pkg-config
            fi
          fi

      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo '/root/.cargo/bin' >> $GITHUB_PATH
          source "$HOME/.cargo/env"
          rustup toolchain install nightly --component rust-src
          rustup target add ${{ matrix.architecture }}-unknown-linux-gnu
          cargo install cross cargo-generate-rpm bpf-linker

      - name: Build and Strip Binary with Cross
        run: |
          source "$HOME/.cargo/env"
          cd ${{ matrix.package }}
          cross build --target ${{ matrix.architecture }}-unknown-linux-gnu --bin ${{ matrix.package }} --release --all-features
          strip target/${{ matrix.architecture }}-unknown-linux-gnu/release/${{ matrix.package }}

      - name: Generate RPM
        run: |
          source "$HOME/.cargo/env"
          cd ${{ matrix.package }}
          cargo generate-rpm --package ${{ matrix.package }} --target ${{ matrix.architecture }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-${{ matrix.os_image }}-${{ matrix.architecture }}
          path: ${{ matrix.package }}/target/*/generate-rpm/*.rpm
